what is git

git is a source code manegment 
ald version control system 
 in git you can used to the all command thats why you can
 use git all command


this is my commit i have work this commit
 i will add and commit in this file after that you can changes that 
 file

